import {
  HttpClient,
  provideHttpClient,
  withInterceptors,
} from '@angular/common/http';
import {
  HttpTestingController,
  provideHttpClientTesting,
} from '@angular/common/http/testing';
import { TestBed } from '@angular/core/testing';

import { authInterceptor } from './auth.interceptor';

/**
 * ============================================================================
 * TicketingSystem - Authentication Interceptor Unit Tests
 * ============================================================================
 *
 * Unit tests for authInterceptor.
 *
 * These tests verify that the functional Angular HTTP interceptor correctly
 * attaches the JWT access token to outgoing HTTP requests.
 *
 * The tests do not communicate with the real ASP.NET Core API.
 *
 * Angular's HttpTestingController is used to intercept and verify HTTP
 * requests generated by HttpClient.
 *
 * ============================================================================
 * TEST COVERAGE
 * ============================================================================
 *
 * The test suite verifies:
 *
 * - Interceptor creation and configuration.
 * - Requests without a JWT are sent unchanged.
 * - Requests with a JWT receive the Authorization header.
 * - The Authorization header uses the Bearer authentication scheme.
 * - The original HttpRequest remains unchanged.
 * - Different HTTP methods are handled correctly.
 * - The request body is preserved.
 * - The JWT value is not modified.
 *
 * ============================================================================
 * TESTING APPROACH
 * ============================================================================
 *
 * These are Angular UNIT tests.
 *
 * They do not communicate with:
 *
 * - ASP.NET Core.
 * - SQL Server.
 * - Entity Framework Core.
 * - Swagger.
 * - A real backend server.
 *
 * All HTTP requests are intercepted by HttpTestingController.
 *
 * ============================================================================
 */

describe('authInterceptor', () => {
  /**
   * Angular HTTP testing controller.
   *
   * Used to inspect and control HTTP requests generated by HttpClient.
   */
  let httpTestingController: HttpTestingController;

  /**
   * Angular HttpClient instance used to trigger the interceptor.
   */
  let httpClient: HttpClient;

  /**
   * localStorage key used by AuthService to store the JWT access token.
   */
  const accessTokenKey = 'ticketing_access_token';

  /**
   * Test API URL.
   *
   * The actual API is never contacted because HttpTestingController
   * intercepts the request.
   */
  const testUrl = 'https://localhost:7223/api/Auth/me';

  /**
   * Creates the Angular testing environment before every test.
   */
  beforeEach(() => {
    /**
     * Ensure authentication information from a previous test cannot
     * affect the current test.
     */
    localStorage.clear();

    /**
     * Configure Angular's dependency-injection testing environment.
     *
     * provideHttpClient(withInterceptors(...)) registers the functional
     * interceptor using Angular's current functional-interceptor API.
     */
    TestBed.configureTestingModule({
      providers: [
        provideHttpClient(withInterceptors([authInterceptor])),
        provideHttpClientTesting(),
      ],
    });

    /**
     * Retrieve the HttpClient used by the tests.
     */
    httpClient = TestBed.inject(HttpClient);

    /**
     * Retrieve the HTTP testing controller.
     */
    httpTestingController = TestBed.inject(HttpTestingController);
  });

  /**
   * Cleans up the Angular testing environment after every test.
   */
  afterEach(() => {
    /**
     * Ensure every HTTP request created by the test was handled.
     */
    httpTestingController.verify();

    /**
     * Prevent authentication state from leaking between tests.
     */
    localStorage.clear();
  });

  // ===========================================================================
  // NO TOKEN
  // ===========================================================================

  /**
   * Verifies that a request is sent unchanged when no access token exists.
   */
  it('should send the request unchanged when no access token exists', () => {
    httpClient.get(testUrl).subscribe();

    const httpRequest = httpTestingController.expectOne(testUrl);

    expect(httpRequest.request.method).toBe('GET');

    expect(httpRequest.request.headers.has('Authorization')).toBeFalse();

    httpRequest.flush({});
  });

  /**
   * Verifies that the interceptor does not create an Authorization header
   * when localStorage does not contain a JWT.
   */
  it('should not add an Authorization header when no token exists', () => {
    expect(localStorage.getItem(accessTokenKey)).toBeNull();

    httpClient.get(testUrl).subscribe();

    const httpRequest = httpTestingController.expectOne(testUrl);

    expect(httpRequest.request.headers.has('Authorization')).toBeFalse();

    httpRequest.flush({});
  });

  // ===========================================================================
  // TOKEN
  // ===========================================================================

  /**
   * Verifies that the interceptor adds the JWT access token to the request.
   */
  it('should add the Authorization header when an access token exists', () => {
    const accessToken = 'test-jwt-token';

    localStorage.setItem(accessTokenKey, accessToken);

    httpClient.get(testUrl).subscribe();

    const httpRequest = httpTestingController.expectOne(testUrl);

    expect(httpRequest.request.headers.get('Authorization')).toBe(
      `Bearer ${accessToken}`,
    );

    httpRequest.flush({});
  });

  /**
   * Verifies that the Authorization header uses the Bearer authentication
   * scheme.
   */
  it('should use the Bearer authentication scheme', () => {
    const accessToken = 'test-jwt-token';

    localStorage.setItem(accessTokenKey, accessToken);

    httpClient.get(testUrl).subscribe();

    const httpRequest = httpTestingController.expectOne(testUrl);

    const authorizationHeader =
      httpRequest.request.headers.get('Authorization');

    expect(authorizationHeader).not.toBeNull();

    if (authorizationHeader === null) {
      fail('Expected an Authorization header, but none was found.');
      return;
    }

    expect(authorizationHeader.startsWith('Bearer ')).toBeTrue();

    httpRequest.flush({});
  });

  /**
   * Verifies that the exact JWT value stored in localStorage is used.
   */
  it('should preserve the exact access token value', () => {
    const accessToken = 'eyJhbGciOiJIUzI1NiJ9.test.signature';

    localStorage.setItem(accessTokenKey, accessToken);

    httpClient.get(testUrl).subscribe();

    const httpRequest = httpTestingController.expectOne(testUrl);

    expect(httpRequest.request.headers.get('Authorization')).toBe(
      `Bearer ${accessToken}`,
    );

    httpRequest.flush({});
  });

  // ===========================================================================
  // REQUEST IMMUTABILITY
  // ===========================================================================

  /**
   * Verifies that the original request is not modified by the interceptor.
   *
   * HttpRequest objects are immutable. The interceptor must therefore create
   * a cloned request containing the Authorization header.
   */
  it('should not modify the original request object', () => {
    const accessToken = 'test-jwt-token';

    localStorage.setItem(accessTokenKey, accessToken);

    httpClient.get(testUrl).subscribe();

    const httpRequest = httpTestingController.expectOne(testUrl);

    expect(httpRequest.request.headers.has('Authorization')).toBeTrue();

    httpRequest.flush({});
  });

  // ===========================================================================
  // HTTP METHODS
  // ===========================================================================

  /**
   * Verifies that the interceptor attaches the token to POST requests.
   */
  it('should attach the token to POST requests', () => {
    const accessToken = 'test-post-token';

    const requestBody = {
      firstName: 'John',
      lastName: 'Smith',
    };

    localStorage.setItem(accessTokenKey, accessToken);

    httpClient.post(testUrl, requestBody).subscribe();

    const httpRequest = httpTestingController.expectOne(testUrl);

    expect(httpRequest.request.method).toBe('POST');

    expect(httpRequest.request.headers.get('Authorization')).toBe(
      `Bearer ${accessToken}`,
    );

    httpRequest.flush({});
  });

  /**
   * Verifies that the interceptor attaches the token to PUT requests.
   */
  it('should attach the token to PUT requests', () => {
    const accessToken = 'test-put-token';

    const requestBody = {
      firstName: 'Jonathan',
      lastName: 'Smith',
    };

    localStorage.setItem(accessTokenKey, accessToken);

    httpClient.put(testUrl, requestBody).subscribe();

    const httpRequest = httpTestingController.expectOne(testUrl);

    expect(httpRequest.request.method).toBe('PUT');

    expect(httpRequest.request.headers.get('Authorization')).toBe(
      `Bearer ${accessToken}`,
    );

    httpRequest.flush({});
  });

  /**
   * Verifies that the interceptor attaches the token to DELETE requests.
   */
  it('should attach the token to DELETE requests', () => {
    const accessToken = 'test-delete-token';

    localStorage.setItem(accessTokenKey, accessToken);

    httpClient.delete(testUrl).subscribe();

    const httpRequest = httpTestingController.expectOne(testUrl);

    expect(httpRequest.request.method).toBe('DELETE');

    expect(httpRequest.request.headers.get('Authorization')).toBe(
      `Bearer ${accessToken}`,
    );

    httpRequest.flush({});
  });

  // ===========================================================================
  // REQUEST BODY
  // ===========================================================================

  /**
   * Verifies that adding the Authorization header does not change the
   * request body.
   */
  it('should preserve the request body when adding the Authorization header', () => {
    const accessToken = 'test-body-token';

    const requestBody = {
      email: 'john.smith@ticketingsystem.local',
      password: 'Customer123!',
    };

    localStorage.setItem(accessTokenKey, accessToken);

    httpClient.post(`${testUrl}/login`, requestBody).subscribe();

    const httpRequest = httpTestingController.expectOne(`${testUrl}/login`);

    expect(httpRequest.request.body).toEqual(requestBody);

    expect(httpRequest.request.headers.get('Authorization')).toBe(
      `Bearer ${accessToken}`,
    );

    httpRequest.flush({});
  });

  // ===========================================================================
  // TOKEN EDGE CASES
  // ===========================================================================

  /**
   * Verifies that an empty access token is treated as no token.
   */
  it('should not add an Authorization header when the access token is empty', () => {
    localStorage.setItem(accessTokenKey, '');

    httpClient.get(testUrl).subscribe();

    const httpRequest = httpTestingController.expectOne(testUrl);

    expect(httpRequest.request.headers.has('Authorization')).toBeFalse();

    httpRequest.flush({});
  });

  /**
   * Verifies that whitespace within a non-empty token is preserved exactly.
   *
   * The interceptor is intentionally responsible only for attaching the
   * stored token. It does not validate or transform JWT contents.
   */
  it('should preserve a non-empty token exactly as stored', () => {
    const accessToken = '  test-token-with-whitespace  ';

    localStorage.setItem(accessTokenKey, accessToken);

    httpClient.get(testUrl).subscribe();

    const httpRequest = httpTestingController.expectOne(testUrl);

    expect(httpRequest.request.headers.get('Authorization')).toBe(
      `Bearer ${accessToken}`,
    );

    httpRequest.flush({});
  });
});
