import { TestBed } from '@angular/core/testing';
import {
  HttpClientTestingModule,
  HttpTestingController,
} from '@angular/common/http/testing';
import { Subscription } from 'rxjs';

import { environment } from '../../../environments/environment';

import { AuthService } from './auth.service';

import {
  CurrentUser,
  LoginRequest,
  LoginResponse,
  UpdateCurrentUserRequest,
} from '../../models/authentication.models';

/**
 * ============================================================================
 * TicketingSystem - Authentication Service Unit Tests
 * ============================================================================
 *
 * Unit tests for AuthService.
 *
 * These tests verify the client-side authentication behavior without starting
 * the real ASP.NET Core API.
 *
 * Angular's HttpClientTestingModule is used to intercept HTTP requests and
 * provide controlled responses.
 *
 * ============================================================================
 * TEST COVERAGE
 * ============================================================================
 *
 * The test suite verifies:
 *
 * - Service creation.
 * - Login API requests.
 * - JWT access-token storage.
 * - Current-user storage after login.
 * - currentUser$ notifications.
 * - GET /Auth/me.
 * - Current-user synchronization after GET /Auth/me.
 * - PUT /Auth/me.
 * - Current-user synchronization after profile updates.
 * - isAuthenticated().
 * - getAccessToken().
 * - getCurrentUserValue().
 * - getStoredCurrentUser().
 * - Invalid localStorage data handling.
 * - logout().
 * - Authentication-state cleanup during logout.
 * - BehaviorSubject notifications during logout.
 *
 * ============================================================================
 * TESTING APPROACH
 * ============================================================================
 *
 * These are Angular UNIT tests.
 *
 * They do not communicate with:
 *
 * - ASP.NET Core.
 * - SQL Server.
 * - Entity Framework Core.
 * - Swagger.
 * - A real backend server.
 *
 * HTTP requests are intercepted by HttpTestingController.
 *
 * ============================================================================
 */
describe('AuthService', () => {
  /**
   * AuthService instance under test.
   */
  let service: AuthService;

  /**
   * Angular HTTP testing controller.
   *
   * Used to inspect and control HTTP requests generated by AuthService.
   */
  let httpTestingController: HttpTestingController;

  /**
   * API base URL used by AuthService.
   */
  const apiUrl = environment.apiUrl;

  /**
   * localStorage key used for the JWT access token.
   */
  const accessTokenKey = 'ticketing_access_token';

  /**
   * localStorage key used for the current authenticated user.
   */
  const currentUserKey = 'ticketing_current_user';

  /**
   * Standard test email address.
   */
  const testEmail = 'john.smith@ticketingsystem.local';

  /**
   * Standard updated test email address.
   */
  const updatedTestEmail = 'jonathan.smith@ticketingsystem.local';

  /**
   * Creates a standard test user.
   *
   * @returns A valid CurrentUser object for unit tests.
   */
  const createCurrentUser = (): CurrentUser => ({
    userId: 'test-user-id',
    firstName: 'John',
    lastName: 'Smith',
    fullName: 'John Smith',
    email: testEmail,
    role: 'Customer',
  });

  /**
   * Creates a standard login response.
   *
   * @returns A valid LoginResponse object for unit tests.
   */
  const createLoginResponse = (): LoginResponse => ({
    accessToken: 'test-jwt-token',
    userId: 'test-user-id',
    firstName: 'John',
    lastName: 'Smith',
    fullName: 'John Smith',
    email: testEmail,
    role: 'Customer',
  });

  /**
   * Creates a standard login request.
   *
   * @returns A valid LoginRequest object for unit tests.
   */
  const createLoginRequest = (): LoginRequest => ({
    email: testEmail,
    password: 'Customer123!',
  });

  /**
   * Creates a standard profile-update request.
   *
   * @returns A valid UpdateCurrentUserRequest object for unit tests.
   */
  const createUpdateRequest = (): UpdateCurrentUserRequest => ({
    firstName: 'Jonathan',
    lastName: 'Smith',
    email: updatedTestEmail,
  });

  /**
   * Creates the Angular testing environment before every test.
   */
  beforeEach(() => {
    /**
     * Ensure no authentication information from a previous test remains.
     */
    localStorage.clear();

    /**
     * Configure the Angular dependency-injection testing environment.
     */
    TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      providers: [AuthService],
    });

    /**
     * Retrieve the service under test.
     */
    service = TestBed.inject(AuthService);

    /**
     * Retrieve the HTTP testing controller.
     */
    httpTestingController = TestBed.inject(HttpTestingController);
  });

  /**
   * Cleans up the Angular testing environment after every test.
   */
  afterEach(() => {
    /**
     * Ensure every HTTP request created by the test was handled.
     */
    httpTestingController.verify();

    /**
     * Prevent authentication state from leaking between tests.
     */
    localStorage.clear();
  });

  // ===========================================================================
  // SERVICE CREATION
  // ===========================================================================

  /**
   * Verifies that AuthService can be created by Angular.
   */
  it('should be created', () => {
    expect(service).toBeTruthy();
  });

  // ===========================================================================
  // LOGIN
  // ===========================================================================

  /**
   * Verifies that login sends credentials to the correct API endpoint.
   */
  it('should send login credentials to the Auth/login endpoint', () => {
    const request = createLoginRequest();
    const expectedResponse = createLoginResponse();

    service.login(request).subscribe((response) => {
      expect(response).toEqual(expectedResponse);
    });

    const httpRequest = httpTestingController.expectOne(`${apiUrl}/Auth/login`);

    expect(httpRequest.request.method).toBe('POST');
    expect(httpRequest.request.body).toEqual(request);

    httpRequest.flush(expectedResponse);
  });

  /**
   * Verifies that a successful login stores the JWT access token.
   */
  it('should store the access token after successful login', () => {
    const expectedResponse = createLoginResponse();

    service.login(createLoginRequest()).subscribe();

    const httpRequest = httpTestingController.expectOne(`${apiUrl}/Auth/login`);

    httpRequest.flush(expectedResponse);

    expect(localStorage.getItem(accessTokenKey)).toBe(
      expectedResponse.accessToken,
    );
  });

  /**
   * Verifies that a successful login stores the current user.
   */
  it('should store the current user after successful login', () => {
    const expectedResponse = createLoginResponse();

    service.login(createLoginRequest()).subscribe();

    const httpRequest = httpTestingController.expectOne(`${apiUrl}/Auth/login`);

    httpRequest.flush(expectedResponse);

    const storedUserJson = localStorage.getItem(currentUserKey);

    expect(storedUserJson).not.toBeNull();

    const storedUser = JSON.parse(storedUserJson as string) as CurrentUser;

    const expectedUser: CurrentUser = {
      userId: expectedResponse.userId,
      firstName: expectedResponse.firstName,
      lastName: expectedResponse.lastName,
      fullName: expectedResponse.fullName,
      email: expectedResponse.email,
      role: expectedResponse.role,
    };

    expect(storedUser).toEqual(expectedUser);
  });

  /**
   * Verifies that currentUser$ publishes the authenticated user after login.
   */
  it('should publish the current user after successful login', () => {
    const expectedResponse = createLoginResponse();

    let receivedUser: CurrentUser | null = null;

    const subscription: Subscription = service.currentUser$.subscribe(
      (user: CurrentUser | null) => {
        receivedUser = user;
      },
    );

    service.login(createLoginRequest()).subscribe();

    const httpRequest = httpTestingController.expectOne(`${apiUrl}/Auth/login`);

    httpRequest.flush(expectedResponse);

    expect(receivedUser).not.toBeNull();

    if (receivedUser === null) {
      fail('Expected login to publish a CurrentUser, but received null.');
      return;
    }

    expect(receivedUser).toEqual({
      userId: expectedResponse.userId,
      firstName: expectedResponse.firstName,
      lastName: expectedResponse.lastName,
      fullName: expectedResponse.fullName,
      email: expectedResponse.email,
      role: expectedResponse.role,
    });

    subscription.unsubscribe();
  });

  /**
   * Verifies that login HTTP errors are propagated to the caller.
   */
  it('should propagate login HTTP errors', () => {
    let receivedError: unknown = null;

    service.login(createLoginRequest()).subscribe({
      next: () => {
        fail('The login request should not succeed.');
      },
      error: (error: unknown) => {
        receivedError = error;
      },
    });

    const httpRequest = httpTestingController.expectOne(`${apiUrl}/Auth/login`);

    httpRequest.flush(
      {
        message: 'Invalid credentials.',
      },
      {
        status: 401,
        statusText: 'Unauthorized',
      },
    );

    expect(receivedError).toBeTruthy();
  });

  // ===========================================================================
  // GET CURRENT USER
  // ===========================================================================

  /**
   * Verifies that getCurrentUser() sends a GET request to /Auth/me.
   */
  it('should retrieve the current user from the Auth/me endpoint', () => {
    const expectedUser = createCurrentUser();

    service.getCurrentUser().subscribe((user) => {
      expect(user).toEqual(expectedUser);
    });

    const httpRequest = httpTestingController.expectOne(`${apiUrl}/Auth/me`);

    expect(httpRequest.request.method).toBe('GET');

    httpRequest.flush(expectedUser);
  });

  /**
   * Verifies that getCurrentUser() synchronizes localStorage.
   */
  it('should store the user returned by getCurrentUser', () => {
    const expectedUser = createCurrentUser();

    service.getCurrentUser().subscribe();

    const httpRequest = httpTestingController.expectOne(`${apiUrl}/Auth/me`);

    httpRequest.flush(expectedUser);

    const storedUserJson = localStorage.getItem(currentUserKey);

    expect(storedUserJson).not.toBeNull();

    const storedUser = JSON.parse(storedUserJson as string) as CurrentUser;

    expect(storedUser).toEqual(expectedUser);
  });

  /**
   * Verifies that getCurrentUser() publishes the returned user through
   * currentUser$.
   */
  it('should publish the user returned by getCurrentUser', () => {
    const expectedUser = createCurrentUser();

    let receivedUser: CurrentUser | null = null;

    const subscription: Subscription = service.currentUser$.subscribe(
      (user: CurrentUser | null) => {
        receivedUser = user;
      },
    );

    service.getCurrentUser().subscribe();

    const httpRequest = httpTestingController.expectOne(`${apiUrl}/Auth/me`);

    httpRequest.flush(expectedUser);

    expect(receivedUser).not.toBeNull();

    if (receivedUser === null) {
      fail(
        'Expected getCurrentUser() to publish a CurrentUser, but received null.',
      );
      return;
    }

    expect(receivedUser).toEqual(expectedUser);

    subscription.unsubscribe();
  });

  // ===========================================================================
  // UPDATE CURRENT USER
  // ===========================================================================

  /**
   * Verifies that updateCurrentUser() sends the correct PUT request.
   */
  it('should send the profile update to the Auth/me endpoint', () => {
    const request = createUpdateRequest();

    const expectedUser: CurrentUser = {
      userId: 'test-user-id',
      firstName: 'Jonathan',
      lastName: 'Smith',
      fullName: 'Jonathan Smith',
      email: updatedTestEmail,
      role: 'Customer',
    };

    service.updateCurrentUser(request).subscribe((user) => {
      expect(user).toEqual(expectedUser);
    });

    const httpRequest = httpTestingController.expectOne(`${apiUrl}/Auth/me`);

    expect(httpRequest.request.method).toBe('PUT');
    expect(httpRequest.request.body).toEqual(request);

    httpRequest.flush(expectedUser);
  });

  /**
   * Verifies that a successful profile update stores the updated user.
   */
  it('should store the updated user after updateCurrentUser', () => {
    const updatedUser: CurrentUser = {
      userId: 'test-user-id',
      firstName: 'Jonathan',
      lastName: 'Smith',
      fullName: 'Jonathan Smith',
      email: updatedTestEmail,
      role: 'Customer',
    };

    service.updateCurrentUser(createUpdateRequest()).subscribe();

    const httpRequest = httpTestingController.expectOne(`${apiUrl}/Auth/me`);

    httpRequest.flush(updatedUser);

    const storedUserJson = localStorage.getItem(currentUserKey);

    expect(storedUserJson).not.toBeNull();

    const storedUser = JSON.parse(storedUserJson as string) as CurrentUser;

    expect(storedUser).toEqual(updatedUser);
  });

  /**
   * Verifies that a successful profile update publishes the updated user.
   */
  it('should publish the updated user after updateCurrentUser', () => {
    const updatedUser: CurrentUser = {
      userId: 'test-user-id',
      firstName: 'Jonathan',
      lastName: 'Smith',
      fullName: 'Jonathan Smith',
      email: updatedTestEmail,
      role: 'Customer',
    };

    let receivedUser: CurrentUser | null = null;

    const subscription: Subscription = service.currentUser$.subscribe(
      (user: CurrentUser | null) => {
        receivedUser = user;
      },
    );

    service.updateCurrentUser(createUpdateRequest()).subscribe();

    const httpRequest = httpTestingController.expectOne(`${apiUrl}/Auth/me`);

    httpRequest.flush(updatedUser);

    expect(receivedUser).not.toBeNull();

    if (receivedUser === null) {
      fail(
        'Expected updateCurrentUser() to publish a CurrentUser, but received null.',
      );
      return;
    }

    expect(receivedUser).toEqual(updatedUser);

    subscription.unsubscribe();
  });

  // ===========================================================================
  // ACCESS TOKEN
  // ===========================================================================

  /**
   * Verifies that getAccessToken() returns the stored JWT.
   */
  it('should return the stored access token', () => {
    localStorage.setItem(accessTokenKey, 'stored-jwt-token');

    expect(service.getAccessToken()).toBe('stored-jwt-token');
  });

  /**
   * Verifies that getAccessToken() returns null when no token exists.
   */
  it('should return null when no access token exists', () => {
    expect(service.getAccessToken()).toBeNull();
  });

  /**
   * Verifies that isAuthenticated() returns true when a token exists.
   */
  it('should return true from isAuthenticated when an access token exists', () => {
    localStorage.setItem(accessTokenKey, 'stored-jwt-token');

    expect(service.isAuthenticated()).toBeTrue();
  });

  /**
   * Verifies that isAuthenticated() returns false when no access token exists.
   */
  it('should return false from isAuthenticated when no access token exists', () => {
    expect(service.isAuthenticated()).toBeFalse();
  });

  // ===========================================================================
  // CURRENT USER VALUE
  // ===========================================================================

  /**
   * Verifies that getCurrentUserValue() returns the current user
   * synchronously.
   */
  it('should return the current user synchronously', () => {
    const expectedUser = createCurrentUser();

    localStorage.setItem(currentUserKey, JSON.stringify(expectedUser));

    /**
     * Create a fresh service after populating localStorage so the constructor
     * loads the stored user.
     */
    TestBed.resetTestingModule();

    TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      providers: [AuthService],
    });

    const freshService = TestBed.inject(AuthService);

    const actualUser = freshService.getCurrentUserValue();

    expect(actualUser).not.toBeNull();

    if (actualUser === null) {
      fail(
        'Expected getCurrentUserValue() to return a CurrentUser, but received null.',
      );
      return;
    }

    expect(actualUser).toEqual(expectedUser);
  });

  // ===========================================================================
  // STORED CURRENT USER
  // ===========================================================================

  /**
   * Verifies that getStoredCurrentUser() returns null when no user exists.
   */
  it('should return null when no stored current user exists', () => {
    expect(service.getStoredCurrentUser()).toBeNull();
  });

  /**
   * Verifies that getStoredCurrentUser() reads valid JSON from localStorage.
   */
  it('should return the stored current user when valid JSON exists', () => {
    const expectedUser = createCurrentUser();

    localStorage.setItem(currentUserKey, JSON.stringify(expectedUser));

    const actualUser = service.getStoredCurrentUser();

    expect(actualUser).not.toBeNull();

    if (actualUser === null) {
      fail(
        'Expected getStoredCurrentUser() to return a CurrentUser, but received null.',
      );
      return;
    }

    expect(actualUser).toEqual(expectedUser);
  });

  /**
   * Verifies that corrupted localStorage data does not break AuthService.
   *
   * Invalid JSON is removed and null is returned.
   */
  it('should remove corrupted current-user data and return null', () => {
    localStorage.setItem(currentUserKey, '{invalid-json');

    expect(service.getStoredCurrentUser()).toBeNull();

    expect(localStorage.getItem(currentUserKey)).toBeNull();
  });

  // ===========================================================================
  // BEHAVIOR SUBJECT
  // ===========================================================================

  /**
   * Verifies that currentUser$ immediately emits the stored user to a new
   * subscriber.
   *
   * This verifies the BehaviorSubject behavior used by MainLayoutComponent
   * and other application components.
   */
  it('should immediately emit the stored user to new currentUser subscribers', () => {
    const expectedUser = createCurrentUser();

    localStorage.setItem(currentUserKey, JSON.stringify(expectedUser));

    TestBed.resetTestingModule();

    TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      providers: [AuthService],
    });

    const freshService = TestBed.inject(AuthService);

    let receivedUser: CurrentUser | null = null;

    const subscription: Subscription = freshService.currentUser$.subscribe(
      (user: CurrentUser | null) => {
        receivedUser = user;
      },
    );

    expect(receivedUser).not.toBeNull();

    if (receivedUser === null) {
      fail(
        'Expected currentUser$ to immediately emit the stored CurrentUser, but received null.',
      );
      return;
    }

    expect(receivedUser).toEqual(expectedUser);

    subscription.unsubscribe();
  });

  // ===========================================================================
  // LOGOUT
  // ===========================================================================

  /**
   * Verifies that logout removes the stored JWT.
   */
  it('should remove the access token during logout', () => {
    localStorage.setItem(accessTokenKey, 'stored-jwt-token');

    service.logout();

    expect(localStorage.getItem(accessTokenKey)).toBeNull();
  });

  /**
   * Verifies that logout removes the stored current user.
   */
  it('should remove the current user during logout', () => {
    const user = createCurrentUser();

    localStorage.setItem(currentUserKey, JSON.stringify(user));

    service.logout();

    expect(localStorage.getItem(currentUserKey)).toBeNull();
  });

  /**
   * Verifies that logout publishes null through currentUser$.
   */
  it('should publish null through currentUser$ during logout', () => {
    const user = createCurrentUser();

    localStorage.setItem(currentUserKey, JSON.stringify(user));

    /**
     * Create a fresh service because AuthService reads localStorage during
     * construction.
     */
    TestBed.resetTestingModule();

    TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      providers: [AuthService],
    });

    const freshService = TestBed.inject(AuthService);

    let receivedUser: CurrentUser | null = null;

    const subscription: Subscription = freshService.currentUser$.subscribe(
      (currentUser: CurrentUser | null) => {
        receivedUser = currentUser;
      },
    );

    expect(receivedUser).not.toBeNull();

    if (receivedUser === null) {
      fail(
        'Expected currentUser$ to initially emit the stored CurrentUser, but received null.',
      );
      return;
    }

    expect(receivedUser).toEqual(user);

    freshService.logout();

    expect(receivedUser).toBeNull();

    subscription.unsubscribe();
  });

  /**
   * Verifies that logout makes the service unauthenticated.
   */
  it('should become unauthenticated after logout', () => {
    localStorage.setItem(accessTokenKey, 'stored-jwt-token');

    expect(service.isAuthenticated()).toBeTrue();

    service.logout();

    expect(service.isAuthenticated()).toBeFalse();
  });
});
