using TicketingSystem.Application.DTOs.Authentication;
using TicketingSystem.Application.Interfaces;
using TicketingSystem.Application.Services;

namespace TicketingSystem.UnitTests;

/// <summary>
/// Contains focused unit tests for <see cref="AuthenticationService"/>.
///
/// These tests verify the application-level authentication and profile-update
/// business rules without requiring a database, HTTP server, ASP.NET Core
/// application host, or real JWT infrastructure.
///
/// The purpose of these tests is to verify the behavior owned by
/// AuthenticationService while keeping external dependencies isolated.
/// </summary>
public sealed class AuthenticationServiceTests
{
    /// <summary>
    /// Verifies that LoginAsync successfully authenticates a valid user and
    /// returns the login response generated by the JWT token service.
    /// </summary>
    [Fact]
    public async Task LoginAsync_WithValidCredentials_ReturnsLoginResponse()
    {
        // Arrange
        var authenticatedUser = CreateAuthenticatedUser();


    var identityService = new FakeIdentityService
    {
        AuthenticateResult = authenticatedUser,
    };

        var expectedResponse = new LoginResponse
        {
            AccessToken = "test-access-token",
            UserId = authenticatedUser.UserId,
            FirstName = authenticatedUser.FirstName,
            LastName = authenticatedUser.LastName,
            Email = authenticatedUser.Email,
            Role = authenticatedUser.Role,
        };

        var jwtTokenService = new FakeJwtTokenService
        {
            GeneratedResponse = expectedResponse,
        };

        var service = new AuthenticationService(
            identityService,
            jwtTokenService);

        var request = new LoginRequest
        {
            Email = authenticatedUser.Email,
            Password = "ValidPassword123!",
        };

        // Act
        var result = await service.LoginAsync(request);

        // Assert
        Assert.NotNull(result);
        Assert.Equal(expectedResponse.AccessToken, result.AccessToken);
        Assert.Equal(expectedResponse.UserId, result.UserId);
        Assert.Equal(expectedResponse.FirstName, result.FirstName);
        Assert.Equal(expectedResponse.LastName, result.LastName);
        Assert.Equal(expectedResponse.FullName, result.FullName);
        Assert.Equal(expectedResponse.Email, result.Email);
        Assert.Equal(expectedResponse.Role, result.Role);

        Assert.Equal(authenticatedUser.Email, identityService.LastEmail);
        Assert.Equal("ValidPassword123!", identityService.LastPassword);

        Assert.Equal(authenticatedUser.UserId, jwtTokenService.LastUserId);
        Assert.Equal(authenticatedUser.Email, jwtTokenService.LastEmail);
        Assert.Equal(authenticatedUser.FirstName, jwtTokenService.LastFirstName);
        Assert.Equal(authenticatedUser.LastName, jwtTokenService.LastLastName);
        Assert.Equal(authenticatedUser.Role, jwtTokenService.LastRole);
    }

    /// <summary>
    /// Verifies that LoginAsync rejects invalid credentials by throwing an
    /// UnauthorizedAccessException.
    /// </summary>
    [Fact]
    public async Task LoginAsync_WithInvalidCredentials_ThrowsUnauthorizedAccessException()
    {
        // Arrange
        var identityService = new FakeIdentityService
        {
            AuthenticateResult = null,
        };

        var jwtTokenService = new FakeJwtTokenService();

        var service = new AuthenticationService(
            identityService,
            jwtTokenService);

        var request = new LoginRequest
        {
            Email = "invalid@example.com",
            Password = "WrongPassword!",
        };

        // Act
        var exception = await Assert.ThrowsAsync<UnauthorizedAccessException>(
            () => service.LoginAsync(request));

        // Assert
        Assert.Equal(
            "Invalid email address or password.",
            exception.Message);

        Assert.Null(jwtTokenService.LastUserId);
    }

    /// <summary>
    /// Verifies that UpdateCurrentUserAsync returns the updated user when the
    /// identity service successfully updates the profile.
    /// </summary>
    [Fact]
    public async Task UpdateCurrentUserAsync_WithValidUser_ReturnsUpdatedUser()
    {
        // Arrange
        var updatedUser = new AuthenticatedUser
        {
            UserId = "user-001",
            Email = "updated@example.com",
            FirstName = "Updated",
            LastName = "User",
            Role = "Customer",
        };

        var identityService = new FakeIdentityService
        {
            UpdateUserResult = updatedUser,
        };

        var jwtTokenService = new FakeJwtTokenService();

        var service = new AuthenticationService(
            identityService,
            jwtTokenService);

        var request = new UpdateCurrentUserRequest
        {
            FirstName = "Updated",
            LastName = "User",
            Email = "updated@example.com",
        };

        // Act
        var result = await service.UpdateCurrentUserAsync(
            updatedUser.UserId,
            request);

        // Assert
        Assert.NotNull(result);
        Assert.Equal(updatedUser.UserId, result.UserId);
        Assert.Equal(updatedUser.Email, result.Email);
        Assert.Equal(updatedUser.FirstName, result.FirstName);
        Assert.Equal(updatedUser.LastName, result.LastName);
        Assert.Equal(updatedUser.Role, result.Role);

        Assert.Equal(updatedUser.UserId, identityService.LastUserId);
        Assert.Equal(request.FirstName, identityService.LastFirstName);
        Assert.Equal(request.LastName, identityService.LastLastName);
        Assert.Equal(request.Email, identityService.LastUpdateEmail);
    }

    /// <summary>
    /// Verifies that UpdateCurrentUserAsync throws an
    /// UnauthorizedAccessException when the identity service cannot find the
    /// authenticated user.
    /// </summary>
    [Fact]
    public async Task UpdateCurrentUserAsync_WhenUserDoesNotExist_ThrowsUnauthorizedAccessException()
    {
        // Arrange
        var identityService = new FakeIdentityService
        {
            UpdateUserResult = null,
        };

        var jwtTokenService = new FakeJwtTokenService();

        var service = new AuthenticationService(
            identityService,
            jwtTokenService);

        var request = new UpdateCurrentUserRequest
        {
            FirstName = "Updated",
            LastName = "User",
            Email = "updated@example.com",
        };

        // Act
        var exception = await Assert.ThrowsAsync<UnauthorizedAccessException>(
            () => service.UpdateCurrentUserAsync(
                "missing-user",
                request));

        // Assert
        Assert.Equal(
            "The authenticated user could not be found.",
            exception.Message);

        Assert.Equal("missing-user", identityService.LastUserId);
    }

    /// <summary>
    /// Creates a representative authenticated user used by the login tests.
    /// </summary>
    /// <returns>A test authenticated user.</returns>
    private static AuthenticatedUser CreateAuthenticatedUser()
    {
        return new AuthenticatedUser
        {
            UserId = "user-001",
            Email = "customer@example.com",
            FirstName = "Test",
            LastName = "Customer",
            Role = "Customer",
        };
    }

    /// <summary>
    /// Minimal fake implementation of <see cref="IIdentityService"/>.
    ///
    /// This fake deliberately records the values supplied by the application
    /// service so that the tests can verify that dependencies were called with
    /// the expected information.
    /// </summary>
    private sealed class FakeIdentityService : IIdentityService
    {
        /// <summary>
        /// Gets or sets the user returned by AuthenticateAsync.
        /// </summary>
        public AuthenticatedUser? AuthenticateResult { get; set; }

        /// <summary>
        /// Gets or sets the user returned by UpdateUserAsync.
        /// </summary>
        public AuthenticatedUser? UpdateUserResult { get; set; }

        /// <summary>
        /// Gets the last email supplied to AuthenticateAsync.
        /// </summary>
        public string? LastEmail { get; private set; }

        /// <summary>
        /// Gets the last password supplied to AuthenticateAsync.
        /// </summary>
        public string? LastPassword { get; private set; }

        /// <summary>
        /// Gets the last user identifier supplied to UpdateUserAsync.
        /// </summary>
        public string? LastUserId { get; private set; }

        /// <summary>
        /// Gets the last first name supplied to UpdateUserAsync.
        /// </summary>
        public string? LastFirstName { get; private set; }

        /// <summary>
        /// Gets the last last name supplied to UpdateUserAsync.
        /// </summary>
        public string? LastLastName { get; private set; }

        /// <summary>
        /// Gets the last email supplied to UpdateUserAsync.
        /// </summary>
        public string? LastUpdateEmail { get; private set; }

        /// <inheritdoc />
        public Task<AuthenticatedUser?> AuthenticateAsync(
            string email,
            string password)
        {
            LastEmail = email;
            LastPassword = password;

            return Task.FromResult(AuthenticateResult);
        }

        /// <inheritdoc />
        public Task<AuthenticatedUser?> UpdateUserAsync(
            string userId,
            string firstName,
            string lastName,
            string email)
        {
            LastUserId = userId;
            LastFirstName = firstName;
            LastLastName = lastName;
            LastUpdateEmail = email;

            return Task.FromResult(UpdateUserResult);
        }
    }

    /// <summary>
    /// Minimal fake implementation of <see cref="IJwtTokenService"/>.
    ///
    /// The fake avoids generating real JWT tokens during unit tests because
    /// token generation itself is an infrastructure concern and will be
    /// tested separately where appropriate.
    /// </summary>
    private sealed class FakeJwtTokenService : IJwtTokenService
    {
        /// <summary>
        /// Gets or sets the response returned by GenerateToken.
        /// </summary>
        public LoginResponse GeneratedResponse { get; set; } = new()
        {
            AccessToken = "default-test-token",
        };

        /// <summary>
        /// Gets the last user identifier supplied to GenerateToken.
        /// </summary>
        public string? LastUserId { get; private set; }

        /// <summary>
        /// Gets the last email supplied to GenerateToken.
        /// </summary>
        public string? LastEmail { get; private set; }

        /// <summary>
        /// Gets the last first name supplied to GenerateToken.
        /// </summary>
        public string? LastFirstName { get; private set; }

        /// <summary>
        /// Gets the last last name supplied to GenerateToken.
        /// </summary>
        public string? LastLastName { get; private set; }

        /// <summary>
        /// Gets the last role supplied to GenerateToken.
        /// </summary>
        public string? LastRole { get; private set; }

        /// <inheritdoc />
        public LoginResponse GenerateToken(
            string userId,
            string email,
            string firstName,
            string lastName,
            string role)
        {
            LastUserId = userId;
            LastEmail = email;
            LastFirstName = firstName;
            LastLastName = lastName;
            LastRole = role;

            return GeneratedResponse;
        }
    }

}
